### PR TITLE
Save 'pure' snapshots

### PR DESCRIPTION
**Pull request by kiequoo**
Possible fix for issue https://github.com/strongtyped/fun-cqrs/issues/33

### CODE REVIEW

**Comment by kiequoo** [comment]
Yes the tests fail, maybe this is a no go but i'll try and fix...

**Comment by rcavalcanti** [comment]
I don't see any failing tests. What are you talking about?

**Comment by kiequoo** [comment]
I fixed the test, squashed and force pushed the branch after making that comment, sorry for the confusion :)

Cheers
Dan Brooke

**Comment by kiequoo** [comment]
Hi Renato, any chance of cherry-picking this commit into the master branch to make a 0.0.6.2 release?  It would help me greatly!  Thanks

**Comment by rcavalcanti** [comment]
For sure. I will do it as soon I arrive at the office

**Comment by rcavalcanti** [comment]
Release 0.0.6.2 should show up on maven central soon.

BTW, this four number version sucks. We'll fix it on the next major release. :-)

**Pull request merged**
