### PR TITLE
Allow Projection.receiveEvent PF to return Future[Any] instead of Future[Unit]

### PR DESCRIPTION
**Pull request by kiequoo**
The reason being that my projection is using a slick based repo which returns Futures of various types and I currently have to do `.map(_ => Unit)` on them which is annoying.

### CODE REVIEW

**Comment by rcavalcanti** [comment]
I'm not sure if this is a good reason for returning a Future[Any]. 

Instead we could have Projection[+T] which will allow us to:
```scala
trait Foo

case class Bar(n:String) extends Foo
case class Baz(n:String) extends Foo

val pf1: Projection[Bar] = Projection.empty
val pf2: Projection[Baz] = Projection.empty

val pf3: Projection[Foo]  = pf1 orElse pf2
```

**Comment by rcavalcanti** [comment]
Hmm, my proposal won't work because of:
```scala
Future.successful(())
```

**Comment by rcavalcanti** [comment]
Which bring us to the conclusion that if we want to use the type returned in the Future we'll always need to cast it (if possible runtime exceptions).

We'll never know if a successful Future[Any] is a Future[Foo] because the PF was defined for the Event or if it's a Future[Unit].

Need to think more about it...

**Comment by kiequoo** [comment]
A played around with it a bit and defined onEvent as

```scala
  final def onEvent(evt: DomainEvent): Future[Option[T]] = {
    if (receiveEvent.isDefinedAt(evt)) {
      import scala.concurrent.ExecutionContext.Implicits.global
      receiveEvent(evt).map(Some(_))
    }
    else {
      Future.successful(None)
    }
  }
``` 

The types end up spilling into a lot of places though so i'm not convinced.  But let me know what you think :)

**Comment by rcavalcanti** [comment]
Hi @kiequoo,

Sorry for the delay. I was out for some days. 

I was trying with the following code:

```scala
final def onEvent(evt: DomainEvent): Future[A] = {
    if (receiveEvent.isDefinedAt(evt)) {
      receiveEvent(evt)
    }
    else {
      Future.failed(new ProjectionNotDefined(evt))
    }
  }
```

Since the code that'll be calling onEvent is internal to Fun.CQRS we can easily recover from it without the need to wrap it in an Option.

However, I'm not yet convinced this will give a decent solution.
We need to consider the andThen and orElse compositions as well. If we have Projection[Baz] and Projection[Bar], what will be the type of `andThen` composition? Projection[List[Foo]]?

And what about `Projection[List[Baz]] andThen Projection[Bar]`?

**Comment by rcavalcanti** [comment]
Hi @kiequoo,

I played around with some options and with your last commit. 

I still see this change as problematic, because the `andThen` composition will need to have a Semigroup in order to append the results. This could be a good solution and probably the good one for the future, but I would like to avoid any dependency on Scalaz or Cats for the moment.

Your proposal with Option and a tuple for the `andThen` composition bring us to another problem. If we have only two projection it works perfectly:
```scala
val a : Projection[(Option[T], Option[T])] = projA andThen projB
```
but as soon we have more than two projections, things start to get very hairy:
```scala
val a : Projection[((Option[T], Option[T]), Option[T])] = projA andThen projB andThen projC
```
I would like to avoid it. 
We can solve it with Monoid/Semigroup. Monoid will also solve the problem of which value to return when the PF is not defined.

**Comment by rcavalcanti** [comment]
Would it be acceptable for you to have the following on your project:
```scala
trait TypedProjection[T] { 
  self =>

  def receiveEvent: PartialFunction[DomainEvent, Future[T]]

  final def onEvent(evt: DomainEvent): Future[Option[T]] = {
    if (receiveEvent.isDefinedAt(evt)) {
      import scala.concurrent.ExecutionContext.Implicits.global
      receiveEvent(evt).map(Option(_))
    } else {
      Future.successful(None)
    }
  }

  def asProjection : Projection = new Projection {
    import scala.concurrent.ExecutionContext.Implicits.global
    def receiveEvent: HandleEvent = {
      case any if self.receiveEvent.isDefinedAt(any) =>
        self.receiveEvent(any).map(_ => Unit)
    }
  }
}
```

This projection can work with the types from your repo and whenever you need to use it in a Fun.CQRS projection actor you can wrap it in a Projection returning Future[Unit].

Note that for the ProjectionActor its really makes no sense to have a type other than Unit as it can do nothing with it.

**Comment by kiequoo** [comment]
Will try and check this out again over the weekend!

**Pull request closed without merging**
