### PR TITLE
Fixed bug if exception is returned during Uninitialized state

### PR DESCRIPTION
**Pull request by kiequoo**
During initialReceive of AggregateActor, if the behaviour returned an exception, the AggregateActor would incorrectly revert from Busy back to Available rather than Uninitialized.

### CODE REVIEW

**Comment by rcavalcanti** [comment]
Thanks Dan! 

I didn't know you were already using Fun.CQRS. 

I'll try to avoid breaking changes without communicating with you.

**Comment by kiequoo** [comment]
You're welcome! I just converted my project to use Fun.CQRS yesterday :)

**Comment by rcavalcanti** [comment]
I invite you to check the options I added to save the offset of the projections
https://github.com/strongtyped/fun-cqrs/commit/2958a1131b7d4d871159e1c483b707d915072395

**Comment by kiequoo** [comment]
Looks good, i’m going to implement a projection with a repo stored in a postgres DB over the next few days so i’ll let you know how I get on with this :)

-- 
Dan Brooke
Sent with Airmail

On 20 October 2015 at 10:31:42, Renato Cavalcanti (notifications@github.com) wrote:

I invite you to check the options I added to save the offset of the projections
2958a11

**Pull request merged**
