### PR TITLE
Upgrade to Akka 2.4.2

### PR DESCRIPTION
**Pull request by kiequoo**
Hi Renato!  I know development has moved on a long way from the master branch, but I am using the last release version 0.1.1 in a project and would like to upgrade to akka 2.4.2 and non experimental akka-streams.  Any chance you could merge this and do a quick release?  Would be very helpful, thanks!

### CODE REVIEW

**Comment by kiequoo** [comment]
PS the new DSL is looking really good and i'll happily upgrade when you get to a release version :)

**Comment by rcavalcanti** [comment]
Hi @kiequoo,

It's merged. I'll publish the artifact right now. 

Thanks for the upgrade.

**Comment by rcavalcanti** [comment]
published!

**Comment by rcavalcanti** [comment]
About the DSL, yes. It moved a lot. I did lots of experiments and incorporated some feedback I got from the DDD community. 

Unfortunately it comes with considerable refactoring if you migrate to it. 

I'm planning to release it soon. I just need to work more on the docs. 
Btw, you can read the docs here: www.funcqrs.io ;-)

**Comment by kiequoo** [comment]
Thanks a lot!

**Pull request merged**
